#pragma once

#define AML_PREFIX_BYTE 0x0A
#define AML_PREFIX_WORD 0x0B
#define AML_PREFIX_DWORD 0x0C
#define AML_PREFIX_QWORD 0x0E
#define AML_PREFIX_STRING 0x0D
#define AML_PREFIX_EXT_OP 0x5B
#define AML_PREFIX_DUAL_NAME 0x2E


#define AML_NULL_CHAR 0x0
#define AML_ZERO_OP 0x0
#define AML_ONE_OP 0x1
#define AML_ONES_OP 0xFF
#define AML_REVISION_OP 0x5B30

#define AML_OP_ALIAS 0x06
#define AML_OP_NAME 0x08
#define AML_OP_SCOPE 0x10
#define AML_OP_BUFFER 0x11
#define AML_OP_PACKAGE 0x12
#define AML_OP_VARPACKAGE 0x13
#define AML_OP_METHOD 0x14
#define AML_OP_EXTERNAL 0x15
#define AML_OP_

#define AML_FIELD_FLAG_ACCESS_TYPE 0x0F
#define AML_FIELD_FLAG_ACCESS_TYPE_ANY 0
#define AML_FIELD_FLAG_ACCESS_TYPE_BYTE 1
#define AML_FIELD_FLAG_ACCESS_TYPE_WORD 2
#define AML_FIELD_FLAG_ACCESS_TYPE_DWORD 3
#define AML_FIELD_FLAG_ACCESS_TYPE_QWORD 4
#define AML_FIELD_FLAG_ACCESS_TYPE_BUFFER 5
//6-15 are reserved
#define AML_FIELD_FLAG_LOCK_RULE 0x10
#define AML_FIELD_FLAG_LOCK_RULE_NONE 0
#define AML_FIELD_FLAG_LOCK_RULE_LOCK 1
#define AML_FIELD_FLAG_UPDATE_RULE(ff) ((ff>>5)&0x3)
#define AML_FIELD_FLAG_UPDATE_RULE_PRESERVE 0
#define AML_FIELD_FLAG_UPDATE_RULE_WRITE_ONES 1
#define AML_FIELD_FLAG_UPDATE_RULE_WRITE_ZEROS 2