#pragma once

#include <stdint.h>

#define HPET_GENERAL_CAPABILITIES 0x0
#define HPET_GENERAL_CONFIGURATIION 0x10
#define HPET_GENERAL_INT_STATUS 0x20
#define HPET_MAIN_COUNTER_VAL 0xF0
#define HPET_TIMER_BASE_OFFSET(timer) (0x100+(timer*0x20))
#define HPET_TIMER_CONFIG_OFFSET 0x0
#define HPET_TIMER_COMPAR_OFFSET 0x8
#define HPET_TIMER_FSB_INT_OFFSET 0x10

#define HPET_GENERAL_CAPABILITIES_REV(cap) (cap&0xFF)
#define HPET_GENERAL_CAPABILITIES_TIMERS(cap) ((cap>>8)&0x0F)
#define HPET_GENERAL_CAPABILITIES_COUNT_SIZE(cap) ((cap>>13)&0x1)
#define HPET_GENERAL_CAPABILITIES_LEG_ROUTE(cap) ((cap>>15)&0x1)
#define HPET_GENERAL_CAPABILITIES_VENDOR_ID(cap) ((cap>>16)&0xFFFF)
#define HPET_GENERAL_CAPABILITIES_CLOCK_PER(cap) (cap>>32)

#define HPET_GENERAL_CONFIGURATION_ENABLE_CNF 1<<0
#define HPET_GENERAL_CONFIGURATION_ENABLE_LEG 1<<1

#define HPET_GENERAL_INTERRUPT_STATUS(status,timer) ((status>>timer)&0x1)
#define HPET_TIMER_INT_TYPE_CNF 1<<1
#define HPET_TIMER_INT_ENABLE_CNF 1<<2
#define HPET_TIMER_TYPE_CNF 1<<3
#define HPET_TIMER_PER_CAP 1<<4
#define HPET_TIMER_SIZE_CAP 1<<5
#define HPET_TIMER_VAL_SET 1<<6
#define HPET_TIMER_MODE_32 1<<8
#define HPET_TIMER_INT_ROUTE(cfg,v) (((uint64)v<<9)|cfg)
#define HPET_TIMER_FSB_ENABLE 1<<14
#define HPET_TIMER_FSB_DEL_CAP 1<<15
#define HPET_TIMER_INT_ROUTE_CAP(cfg) (cfg>>32)
